# CMake generated Testfile for 
# Source directory: /home/codephantom/Desktop/game/schizo-game/kernel
# Build directory: /home/codephantom/Desktop/game/schizo-game/kernel/build-ue
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_capi "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_capi")
set_tests_properties(test_capi PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_contracts "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_contracts")
set_tests_properties(test_contracts PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_db "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_db")
set_tests_properties(test_db PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_economy "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_economy")
set_tests_properties(test_economy PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_events "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_events")
set_tests_properties(test_events PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_faction "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_faction")
set_tests_properties(test_faction PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_justice "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_justice")
set_tests_properties(test_justice PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_magic "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_magic")
set_tests_properties(test_magic PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_population "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_population")
set_tests_properties(test_population PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_property "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_property")
set_tests_properties(test_property PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_quests "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_quests")
set_tests_properties(test_quests PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_scenario_debts "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_scenario_debts")
set_tests_properties(test_scenario_debts PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_scenario_drought "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_scenario_drought")
set_tests_properties(test_scenario_drought PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_scenario_oaths "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_scenario_oaths")
set_tests_properties(test_scenario_oaths PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_time "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_time")
set_tests_properties(test_time PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
add_test(test_world "/home/codephantom/Desktop/game/schizo-game/kernel/build-ue/test_world")
set_tests_properties(test_world PROPERTIES  WORKING_DIRECTORY "/home/codephantom/Desktop/game/schizo-game/kernel" _BACKTRACE_TRIPLES "/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;19;add_test;/home/codephantom/Desktop/game/schizo-game/kernel/CMakeLists.txt;0;")
