#!/usr/bin/env python3
"""capi_reach.py — A6: which kernel C API calls does Unreal reach yet?

Every `sim_world_*` function declared in kernel/include/sim/CApi*.h is
listed as reached (referenced anywhere in the Unreal sources) or not yet,
with the completion-plan stage that will bring it to the player. The report
is docs/capi-reach.md. `--check` exits 1 when a function has no stage, so
no kernel system can hide from the plan.

Usage: python3 tools/capi_reach.py [--check]
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "kernel" / "include" / "sim"
UNREAL = [ROOT / "unreal" / "Source", ROOT / "unreal" / "Plugins"]
REPORT = ROOT / "docs" / "capi-reach.md"

DECL = re.compile(r"^\s*[\w\s\*]+?\b(sim_world_\w+)\s*\(")
REF = re.compile(r"\b(sim_world_\w+)\b")

# First match wins (on the name without the sim_world_ prefix); the letter is
# the completion-plan stage that brings the call to the player.
STAGE_BY_PATTERN = [
    (r"festival|season|weather", "O"),
    (r"^(quest_|journal_|dialogue_|event_)", "P"),
    (r"^(npc_|hear_rumours|task_at)", "F"),
    (r"verdict", "H"),
    (r"^treat_wounds$", "K"),  # combat medicine (K3), before "eat" and "treaty"
    (r"^treaty", "Q"),         # faction treaties (Q1)
    (r"ward|rite|omen|favour|divine|oath_breaker|purity", "J"),
    (r"^(hunger|thirst|fatigue|eat|drink|need_effects|advance_needs|rest|best_food|best_drink|health)$", "B"),
    (r"^(item_count|give_item|inventory|buy|sell|price|purse|market_open)", "C"),
    (r"^(craft|work)$", "D"),
    (r"attribute|skill|level|xp|talent|calling|specialisation|character_|progression_refusal|rank", "E"),
    (r"attack|combat|wound|bleeding|stance|stamina|catch_breath|duel|surrender|prisoner|ransom|loot|equip|"
     r"skirmish|death_count|is_dead|challenge_leader|morale|repair|recast", "K"),
    (r"standing|faction_tier|oath|^war$|set_war|outlaw|infamy|band_politics|camp|raid|group|band|caravan|"
     r"escort|rob_|encounter|wild_|route_minutes|travel|player_place|search_site|scout|pay_off|herd_head|"
     r"npc_fate|player_wounds", "Q"),
    (r"^(create|destroy|save|load|advance_days|day|date|month_name|moon_|set_need|needs_severity|drought|set_drought)", "A"),
]


def declared(inc_dir: pathlib.Path):
    """(header, name) for every sim_world_* function declared in CApi*.h."""
    out = []
    for header in sorted(pathlib.Path(inc_dir).glob("CApi*.h")):
        for line in header.read_text(encoding="utf-8").splitlines():
            if line.lstrip().startswith("//"):
                continue
            m = DECL.match(line)
            if m:
                out.append((header.name, m.group(1)))
    return out


def referenced(dirs):
    """Every sim_world_* name mentioned in a .cpp/.h under the dirs."""
    names = set()
    for d in dirs:
        for f in pathlib.Path(d).rglob("*"):
            if f.suffix in (".cpp", ".h") and f.is_file():
                names.update(REF.findall(f.read_text(encoding="utf-8", errors="ignore")))
    return names


def stage_for(name: str) -> str:
    short = name.removeprefix("sim_world_")
    for pattern, stage in STAGE_BY_PATTERN:
        if re.search(pattern, short):
            return stage
    return "unassigned"


def main(argv) -> int:
    decls = declared(INCLUDE)
    seen = set()
    rows, unassigned = [], []
    reached = referenced(UNREAL)
    for header, name in decls:
        if name in seen:
            continue
        seen.add(name)
        stage = stage_for(name)
        if stage == "unassigned":
            unassigned.append(name)
        rows.append((header, name, name in reached, stage))
    n_reached = sum(1 for r in rows if r[2])
    lines = [
        "# C API reach — which kernel calls Unreal reaches yet",
        "",
        "Generated by `tools/capi_reach.py` (A6). Every `sim_world_*` call, whether the Unreal code "
        "uses it yet, and the [completion-plan](completion-plan.md) stage that brings it to the player.",
        "",
        f"**{n_reached} of {len(rows)} reached.**",
        "",
        "| Header | Call | Reached | Stage |",
        "|---|---|---|---|",
    ]
    for header, name, is_reached, stage in rows:
        lines.append(f"| {header} | `{name}` | {'yes' if is_reached else 'not yet'} | {stage} |")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{n_reached} of {len(rows)} C API calls reached; report: {REPORT.relative_to(ROOT)}")
    if unassigned:
        print("unassigned (no stage will bring these to the player):", ", ".join(unassigned))
        if "--check" in argv:
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
